SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
    .string "Ah, yes, I have seen some POKéMON\n"
    .string "ferry people across the water!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
    .string "Small trees can be chopped down\n"
    .string "using the move CUT.\p"
    .string "But remember this!\n"
    .string "CUT is an HM technique.\p"
    .string "You don't have to teach it to\n"
    .string "use it outside of battles.\p"
    .string "Having a POKéMON in your party that\n"
    .string "can learn the move is enough.$"

